### ISSUE TITLE
[Enhancement]: <Missing version in KlusterletAddonConfig>

### ISSUE THREAD

**Issue by arslankhanali** [microshift-io/microshift-documentation#208]
#### What would you like to be added:
At (https://github.com/redhat-et/microshift-documentation/blob/60ff164ed9e95e05eeb5e69827e4d722955ebf32/content/en/docs/user-documentation/how-tos/acm-with-microshift.md) KlusterletAddonConfig is missing version
#### Why is this needed:
User will get an error/prompt for version otherwise

#### fix:
``` yaml
cat <<EOF | oc apply -f -
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${CLUSTER_NAME}
spec:
  clusterName: ${CLUSTER_NAME}
  clusterNamespace: ${CLUSTER_NAME}
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  version: 2.1.0
EOF
```
